export interface CourseTemplate {
  id: string;
  emoji: string;
  titleKo: string;
  titleEn: string;
  descKo: string;
  level: string;
  weeks: number;
  type: string;
  style: string;
  goals: string;
  evaluation: string;
  sampleWeeks: Array<{
    week: number; topic: string; objectives: string; activities: string; assessment: string;
  }>;
}

export const COURSE_TEMPLATES: CourseTemplate[] = [
  {
    id: 'basic-conversation',
    emoji: '💬',
    titleKo: '기초 회화: 일상 중국어',
    titleEn: 'Basic Conversation Chinese',
    descKo: 'HSK 1-2 수준의 기초 회화 중심 수업. 인사, 소개, 쇼핑, 음식 주문 등 실생활에서 바로 쓸 수 있는 표현을 배웁니다.',
    level: 'Beginner',
    weeks: 15,
    type: 'Language',
    style: 'Communicative',
    goals: '일상적인 중국어 회화를 자신 있게 할 수 있으며, HSK 2급 수준의 어휘와 문법을 습득한다.',
    evaluation: '참여도 20%, 말하기 평가 40%, 최종 발표 40%',
    sampleWeeks: [
      { week: 1, topic: '你好！인사와 자기소개', objectives: '기본 인사말과 자기소개 표현 익히기', activities: '역할극: 처음 만나는 상황, 이름/나이/직업 묻고 답하기', assessment: '자기소개 1분 스피치' },
      { week: 2, topic: '我的家人 가족 소개', objectives: '가족 관계 어휘 및 소유 표현 학습', activities: '가족 사진 보고 설명하기, 家庭树(가계도) 만들기', assessment: '가족 소개 문단 쓰기' },
      { week: 3, topic: '几点了？시간과 날짜', objectives: '시간·날짜 표현 및 약속 잡기', activities: '시간표 채우기, 일정 묻고 답하기 대화', assessment: '주간 일정표 중국어로 작성' },
      { week: 4, topic: '买东西 쇼핑하기 1', objectives: '숫자, 가격 묻고 답하기', activities: '모의 시장 상황극', assessment: '쇼핑 대화문 작성' },
      { week: 5, topic: '颜色和衣服 색깔과 옷', objectives: '색상 어휘와 옷 관련 표현 학습', activities: '옷차림 묘사하기', assessment: '친구 옷차림 설명하기' },
      { week: 6, topic: '点菜 음식 주문하기', objectives: '중국 음식 이름과 주문 표현 익히기', activities: '식당 역할극 (종업원과 손님)', assessment: '메뉴판 보고 주문하기' },
      { week: 7, topic: '你喜欢吃什么？ 취향 묻기', objectives: '좋아하는 것과 싫어하는 것 표현', activities: '설문조사 활동 (친구 취향 알아보기)', assessment: '좋아하는 음식/음료 소개' },
      { week: 8, topic: '중간고사 및 복습', objectives: '1~7주차 학습 내용 점검', activities: '복습 게임, 말하기 중간 평가', assessment: '중간고사 말하기 평가' },
      { week: 9, topic: '去哪里？ 장소와 위치', objectives: '방향, 위치 어휘와 길 묻기', activities: '지도 보고 길 찾기 롤플레이', assessment: '우리 동네 약도 그리고 설명하기' },
      { week: 10, topic: '怎么走？ 교통수단', objectives: '다양한 교통수단 표현과 이동 방법 설명', activities: '목적지까지 가는 방법 토론', assessment: '대중교통 이용 계획 세우기' },
      { week: 11, topic: '天气怎么样？ 날씨와 계절', objectives: '날씨 표현과 계절별 활동 말하기', activities: '일기예보 발표하기', assessment: '일주일 날씨 일기 작성' },
      { week: 12, topic: '看病 병원 가기', objectives: '신체 부위 어휘와 아픈 증상 표현', activities: '의사와 환자 역할극', assessment: '증상 설명 대화문 작성' },
      { week: 13, topic: '爱好 취미 생활', objectives: '취미 관련 어휘와 여가 활동 묻기', activities: '동호회 모집 포스터 만들기', assessment: '나의 취미 2분 스피치' },
      { week: 14, topic: '旅行 여행 계획', objectives: '여행지 소개와 계획 표현', activities: '가상 중국 여행 계획 세우기', assessment: '여행 계획서 발표' },
      { week: 15, topic: '기말 평가 및 롤플레이', objectives: '한 학기 학습 내용 총정리 및 활용', activities: '종합 상황극 및 피드백', assessment: '최종 말하기 롤플레이 평가' },
    ],
  },
  {
    id: 'movie-chinese',
    emoji: '🎬',
    titleKo: '영화로 배우는 중국어',
    titleEn: 'Chinese Through Cinema',
    descKo: '중국·대만 영화와 드라마 장면을 활용한 HSK 3-4 수준의 실용 중국어 수업.',
    level: 'Intermediate',
    weeks: 15,
    type: 'Language',
    style: 'Communicative',
    goals: '영화 대사를 통해 자연스러운 구어체 중국어를 습득하고 HSK 4급 수준의 표현력을 키운다.',
    evaluation: '영화 감상문 30%, 장면 재연 발표 40%, 기말 단편 영상 제작 30%',
    sampleWeeks: [
      { week: 1, topic: '卧虎藏龙의 대사로 배우는 사자성어', objectives: '영화 속 고사성어 5개 이상 이해하고 활용', activities: '영상 클립 시청, 대사 따라 말하기, 문화 배경 토론', assessment: '감상문 쓰기 (300자)' },
      { week: 2, topic: '请回答 1988 중국어 버전 — 일상 감정 표현', objectives: '감정 어휘 30개 이상 학습', activities: '장면 더빙 연습, 감정 상황 역할극', assessment: '감정 일기 쓰기' },
      { week: 3, topic: '뉴스/다큐 중국어 청취 전략', objectives: '공식적 언어 레지스터와 뉴스 어휘 이해', activities: '뉴스 클립 딕테이션, 키워드 정리', assessment: '뉴스 요약 말하기' },
      { week: 4, topic: '말할 수 없는 비밀 - 청춘과 사랑', objectives: '연애, 감정 교류 관련 회화 표현', activities: '명대사 섀도잉, 상황별 감정 묘사', assessment: '인물에게 편지 쓰기' },
      { week: 5, topic: '이별계약 - 갈등과 화해', objectives: '반대 의견 제시 및 설득 표현', activities: '주인공의 입장에서 변론하기', assessment: '대화문 재구성하기' },
      { week: 6, topic: '소년시절의 너 - 사회 문제 토론', objectives: '사회 문제 관련 어휘 및 의견 논술', activities: '영화 속 사회 문제 찬반 토론', assessment: '짧은 에세이 작성' },
      { week: 7, topic: '나의 소녀시대 - 과거 회상', objectives: '과거 시제 및 경험 표현 심화', activities: '학창 시절 경험 나누기', assessment: '나의 잊지 못할 추억 스피치' },
      { week: 8, topic: '중간 발표 - 명장면 더빙', objectives: '정확한 발음과 감정으로 대사 소화', activities: '2~3인 1조 더빙 시연', assessment: '더빙 완성도 및 발음 평가' },
      { week: 9, topic: '삼생삼세 십리도화 - 판타지와 사극 어휘', objectives: '고전 어휘 및 존칭/겸양 표현', activities: '사극 톤으로 현대 대화 바꾸기', assessment: '고전 단어장 정리' },
      { week: 10, topic: '겨우 서른 - 직장인의 삶', objectives: '직장, 스트레스, 커리어 관련 표현', activities: '이력서 및 자기소개서 중국어로 쓰기', assessment: '모의 면접 시뮬레이션' },
      { week: 11, topic: '유랑지구 - SF와 미래', objectives: '과학 기술 및 추측/가정 표현', activities: '미래 사회 모습 토론', assessment: '상상 글쓰기 (만약 ~라면)' },
      { week: 12, topic: '예능 프로그램 분석', objectives: '중국 최신 유행어 및 슬랭 익히기', activities: '예능 클립 보고 퀴즈 풀기', assessment: '유행어 활용 대화 만들기' },
      { week: 13, topic: '기말 프로젝트 준비 1', objectives: '단편 영상 대본 작성', activities: '조별 대본 회의 및 피드백', assessment: '대본 초안 제출' },
      { week: 14, topic: '기말 프로젝트 준비 2', objectives: '영상 촬영 및 편집', activities: '조별 촬영 및 교사 발음 지도', assessment: '중간 진행 상황 보고' },
      { week: 15, topic: '기말 단편 영상 상영회', objectives: '직접 제작한 중국어 영상 발표 및 감상', activities: '상영회 및 동료 평가', assessment: '최종 영상 결과물 평가' },
    ],
  },
  {
    id: 'business-chinese',
    emoji: '💼',
    titleKo: '비즈니스 중국어',
    titleEn: 'Business Chinese',
    descKo: '직장 환경에서 필요한 HSK 4-5 수준의 비즈니스 중국어. 회의, 협상, 이메일 작성.',
    level: 'Advanced',
    weeks: 12,
    type: 'Mixed',
    style: 'Traditional',
    goals: '중국어로 업무 회의, 비즈니스 협상, 공식 이메일 작성이 가능한 수준에 도달한다.',
    evaluation: '이메일 작성 과제 30%, 모의 협상 40%, 발표 30%',
    sampleWeeks: [
      { week: 1, topic: '公司介绍 회사 소개와 직함', objectives: '조직도·직책 어휘, 공식 자기소개', activities: '회사 소개 PT 준비, 명함 교환 롤플레이', assessment: '회사 소개 이메일 작성' },
      { week: 2, topic: '商务会议 비즈니스 회의 진행', objectives: '회의 진행 표현, 의견 제시 및 동의/반대', activities: '모의 회의 진행, 회의록 작성', assessment: '회의 요약 보고서' },
      { week: 3, topic: '合同与谈判 계약과 협상', objectives: '협상 전략 어휘, 조건 제시 표현', activities: '협상 시뮬레이션, 계약서 핵심 조항 분석', assessment: '협상 결과 보고서' },
      { week: 4, topic: '职场礼仪 비즈니스 매너', objectives: '접대, 방문, 식사 예절 관련 표현', activities: '손님 맞이 상황극', assessment: '의전 계획서 작성' },
      { week: 5, topic: '产品说明 제품 소개', objectives: '제품 특장점 설명 및 마케팅 어휘', activities: '신제품 발표회 시뮬레이션', assessment: '제품 브로슈어 중국어 번역' },
      { week: 6, topic: '价格讨论 가격 협상', objectives: '단가, 할인, 결제 조건 협상', activities: '바이어와 셀러 역할극', assessment: '견적서 작성 및 발송 이메일' },
      { week: 7, topic: '日程安排 일정 조율', objectives: '출장 일정 및 미팅 시간 조율', activities: '전화로 약속 잡기 연습', assessment: '출장 품의서 작성' },
      { week: 8, topic: '投诉与处理 클레임 제기와 처리', objectives: '문제 상황 설명 및 사과/대안 제시', activities: '고객 불만 대응 롤플레이', assessment: '사과 및 대책 이메일 작성' },
      { week: 9, topic: '招聘与面试 채용과 면접', objectives: '인사 관련 어휘 및 면접 질의응답', activities: '모의 채용 면접', assessment: '중문 이력서 완본 제출' },
      { week: 10, topic: '市场调研 시장 조사', objectives: '데이터 분석 및 트렌드 설명 표현', activities: '시장 조사 결과 브리핑', assessment: '시장 동향 보고서 작성' },
      { week: 11, topic: '代理与合作 대리점 및 제휴', objectives: '계약 조건, 권리 의무 설명', activities: '제휴 협상 실전', assessment: '의향서(LOI) 초안 작성' },
      { week: 12, topic: '최종 비즈니스 프로젝트 발표', objectives: '종합 비즈니스 중국어 활용', activities: '모의 사업 제안 발표회', assessment: '최종 제안서 및 발표 평가' },
    ],
  },
  {
    id: 'culture-exploration',
    emoji: '🏯',
    titleKo: '중국 문화 탐구',
    titleEn: 'Chinese Culture Exploration',
    descKo: '음식·명절·예술·역사를 통해 배우는 HSK 3 수준의 문화 중심 중국어 수업.',
    level: 'Intermediate',
    weeks: 15,
    type: 'Culture',
    style: 'Communicative',
    goals: '중국 문화의 다양한 측면을 이해하고 관련 주제로 중국어 토론이 가능하다.',
    evaluation: '문화 탐구 보고서 40%, 수업 참여 30%, 문화 소개 발표 30%',
    sampleWeeks: [
      { week: 1, topic: '春节 춘절과 중국의 새해', objectives: '전통 명절 어휘, 춘절 풍습 이해', activities: '춘련 쓰기, 덕담 표현 배우기', assessment: '춘절 소개 포스터 제작' },
      { week: 2, topic: '中国美食 중국 음식 문화', objectives: '음식 관련 어휘 50개, 음식 주문 표현', activities: '메뉴판 분석, 요리 레시피 읽기', assessment: '좋아하는 중국 음식 소개 글쓰기' },
      { week: 3, topic: '汉字의 기원과 발전', objectives: '상형문자부터 간체자까지 한자 역사 이해', activities: '갑골문 따라 그리기, 부수 학습 게임', assessment: '한자 스토리 만들기' },
      { week: 4, topic: '中国四大发明 중국의 4대 발명', objectives: '역사적 발명품과 과학 관련 기초 어휘', activities: '발명품의 원리 설명하기', assessment: '가장 위대한 발명품 투표 및 이유 설명' },
      { week: 5, topic: '京剧 경극과 전통 예술', objectives: '예술, 공연 관련 어휘 및 경극 분장 의미 파악', activities: '경극 영상 감상 및 배역 맞추기', assessment: '전통 공연 관람기 쓰기' },
      { week: 6, topic: '中国茶文化 중국의 차 문화', objectives: '차의 종류, 다도 관련 표현', activities: '모의 다도 체험 및 차 맛 표현하기', assessment: '차 문화 소개 팸플릿 만들기' },
      { week: 7, topic: '旗袍와 전통 의상', objectives: '치파오의 역사 및 의상 묘사 어휘', activities: '시대별 의상 특징 비교', assessment: '전통 의상 디자인 및 설명' },
      { week: 8, topic: '중간 문화 탐구 발표', objectives: '자유 주제 문화 발표', activities: '3분 문화 소개 스피치', assessment: '발표 및 질의응답 평가' },
      { week: 9, topic: '中秋节 중추절과 달맞이', objectives: '중추절 풍습, 월병, 보름달 관련 어휘', activities: '중추절 전설(창어) 연극', assessment: '명절 축하 카드 작성' },
      { week: 10, topic: '中国式数字 표현 - 숫자의 상징성', objectives: '숫자 해음(길운/액운) 및 손가락 숫자 기호', activities: '숫자 암호 풀기 게임', assessment: '숫자 문화 비교 에세이' },
      { week: 11, topic: '高铁와 중국의 교통 혁명', objectives: '고속철도 탑승, 발전 관련 표현', activities: '기차표 예매 상황극', assessment: '고속철도 여행기 작성' },
      { week: 12, topic: '中国武术 중국 무술 (우슈)', objectives: '태극권, 소림사 등 무술 관련 어휘', activities: '태극권 기본 동작 영상 보고 묘사', assessment: '무술 영화 명장면 리뷰' },
      { week: 13, topic: '微信 WeChat과 현대 디지털 라이프', objectives: '모바일 결제, 홍바오, SNS 관련 최신 어휘', activities: '가상 위챗 모멘트 작성', assessment: '디지털 라이프의 장단점 토론' },
      { week: 14, topic: '淘宝와 전자상거래', objectives: '온라인 쇼핑, 라이브 커머스 표현', activities: '가상 라이브 방송 판매자 역할극', assessment: '상품 리뷰 작성' },
      { week: 15, topic: '기말 종합 문화 포럼', objectives: '한 학기 동안 배운 문화 주제 심층 토론', activities: '주제별 그룹 토론 및 패널 발표', assessment: '문화 탐구 최종 보고서 제출' },
    ],
  },
  {
    id: 'hsk-prep',
    emoji: '📝',
    titleKo: 'HSK 시험 대비반',
    titleEn: 'HSK Exam Preparation',
    descKo: 'HSK 3-4급 시험을 체계적으로 준비하는 전략 중심 수업. 듣기·읽기·쓰기 파트별 전략.',
    level: 'Intermediate',
    weeks: 12,
    type: 'Language',
    style: 'Traditional',
    goals: 'HSK 3급 이상 합격을 목표로 어휘·문법·시험 전략을 체계적으로 학습한다.',
    evaluation: '모의시험 50%, 주간 어휘 테스트 30%, 출석 20%',
    sampleWeeks: [
      { week: 1, topic: 'HSK 3급 핵심 어휘 300 (1)', objectives: 'HSK 3급 어휘 1-100 완전 습득', activities: '플래시카드 게임, 문장 완성 연습', assessment: '어휘 테스트 50문항' },
      { week: 2, topic: '듣기 파트 전략: 핵심 포착법', objectives: '듣기 핵심 정보 파악, 오답 유형 분석', activities: '기출문제 청취 연습, 오답 분석', assessment: '듣기 모의 파트 풀기' },
      { week: 3, topic: '읽기 파트 전략: 빠른 독해법', objectives: '시간 내 지문 독해, 주제 파악', activities: '패러프레이즈 연습, 속독 훈련', assessment: '읽기 모의 파트 풀기' },
      { week: 4, topic: '쓰기 파트 전략: 어순 배열', objectives: '기본 문장 구조(SVO) 및 부사어/관형어 위치', activities: '문장 구조 분석, 어순 맞추기 퀴즈', assessment: '쓰기 1부분 모의 풀이' },
      { week: 5, topic: 'HSK 3급 핵심 어휘 300 (2)', objectives: 'HSK 3급 어휘 101-200 완전 습득', activities: '유의어/반의어 매칭 게임', assessment: '어휘 테스트 50문항' },
      { week: 6, topic: '듣기 파트 심화: 장문 듣고 답하기', objectives: '세부 정보 메모리 전략', activities: '딕테이션, 섀도잉', assessment: '장문 듣기 퀴즈' },
      { week: 7, topic: '읽기 파트 심화: 빈칸 채우기', objectives: '문맥 추론 및 어휘 호응 관계 파악', activities: '짝꿍 단어(콜로케이션) 암기', assessment: '빈칸 채우기 20문항' },
      { week: 8, topic: '쓰기 파트 심화: 한자 쓰기', objectives: '빈출 한자 암기 및 획순', activities: '받아쓰기, 한자 부수 연상법', assessment: '쓰기 2부분 집중 연습' },
      { week: 9, topic: 'HSK 3급 핵심 어휘 300 (3)', objectives: 'HSK 3급 어휘 201-300 및 4급 맛보기', activities: '누적 어휘 골든벨', assessment: '어휘 최종 테스트' },
      { week: 10, topic: '문법 총정리: 특수 구문', objectives: '把자문, 被자문, 비교문 등 완벽 이해', activities: '오류 문장 고치기', assessment: '문법 종합 평가' },
      { week: 11, topic: '실전 모의고사 1', objectives: '실제 시험 시간 배분 및 실전 감각 배양', activities: '타이머 설정 후 실전 풀이', assessment: '모의고사 1회 채점 및 오답노트' },
      { week: 12, topic: '실전 모의고사 2 및 최종 점검', objectives: '약점 보완 및 최종 시험 전략 수립', activities: '약점 파트 집중 리뷰', assessment: '모의고사 2회 및 개별 피드백' },
    ],
  },
];
